package com.advantech.model.db2;
// Generated 2020/7/1 下午 05:20:27 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.voodoodyne.jackson.jsog.JSOGGenerator;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users",
         catalog = "lacking"
)
@JsonIdentityInfo(generator = JSOGGenerator.class)
public class Users implements java.io.Serializable {

    private String id;
    private Teams teams;
    private Integer permission;
    private String passHash;
    private String name;
    private String mail;
    private Set<Orders> orderses = new HashSet<Orders>(0);

    public Users() {
    }

    public Users(String id, Teams teams, String passHash) {
        this.id = id;
        this.teams = teams;
        this.passHash = passHash;
    }

    public Users(String id, Teams teams, Integer permission, String passHash, String name, String mail, Set<Orders> orderses) {
        this.id = id;
        this.teams = teams;
        this.permission = permission;
        this.passHash = passHash;
        this.name = name;
        this.mail = mail;
        this.orderses = orderses;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false, length = 10)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "team_id", nullable = false)
    public Teams getTeams() {
        return this.teams;
    }

    public void setTeams(Teams teams) {
        this.teams = teams;
    }

    @Column(name = "permission")
    public Integer getPermission() {
        return this.permission;
    }

    public void setPermission(Integer permission) {
        this.permission = permission;
    }

    @Column(name = "pass_hash", nullable = false, length = 36)
    public String getPassHash() {
        return this.passHash;
    }

    public void setPassHash(String passHash) {
        this.passHash = passHash;
    }

    @Column(name = "name", length = 20)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "mail", length = 40)
    public String getMail() {
        return this.mail;
    }

    public void setMail(String mail) {
        this.mail = mail;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
    public Set<Orders> getOrderses() {
        return this.orderses;
    }

    public void setOrderses(Set<Orders> orderses) {
        this.orderses = orderses;
    }

}
